### ISSUE TITLE
Server Listings Service Completely Down

### ISSUE THREAD

**Issue by LCAdmin** [ATLauncher/Website-Issues#38]
Up-time is not monitored accurately at all. The current up-time says, "X% for past 0 days" despite listings having existed even 3 months sometimes. Voting doesn't work, or it at least hardly works. Haven't had the opportunity to test if the counter works on the website, but the vote packet is not sent to the minecraft server.

**Comment by RyanTheAllmighty** [comment]
Not exactly sure what happened there, seems like the querying server just completely gave up

It should be okay now, but as we tweak this new system over the coming weeks, the votes will get reset and things hopefully won't crash again :P

**Comment by LCAdmin** [comment]
If you're not aware, it seems that it crashed again.

**Comment by RyanTheAllmighty** [comment]
Yup. I've fixed the Votifier packets not being sent off so they should go through all fine and dandy now.

As for the uptime, I may need to completely remove the uptime stuff since there isn't much I can do to keep it stable without it costing extra in server costs.

I'll continue to play around with it to try to get it stable and remove the false negatives
