### ISSUE TITLE
Unorganized Mod Permission Table on the wiki

### ISSUE THREAD

**Issue by dungeonmaster372** [ATLauncher/Website-Issues#44]
Hello Everyone,

The name is Dunge, and I didn't know where else to post this message.  I initially wanted to post a thread on the forums but didnt know where to post it.  However I clicked on support and it brought me here.  So I hope that this gets to the right people.

I was wondering if you guys would like some help with your permissions table.  I am an experienced Mod Pack Dev and staff on FTB.  I may be leaving the team in the near future.  I just noticed how jumbled the mod permission table on the wiki is sorted and I am not trying to bash it but I feel it could use some work.  I have already started working on a google spreadsheet for my personal use, cause the spreadsheet on the wiki is really hard to find what I am looking for due to everything being in random chaotic order.

you can send me a message via the forums if you like.  My name there is dunge, just signed up last night.  I look forward to hosting my pack "DM Teck Mix 2.0" soon on your launcher as soon as I can get this spreadsheet organized enough for me to find all the info to submit.

Thanks again for your time,
Your Friend,
Dunge

**Comment by RyanTheAllmighty** [comment]
We're in the process of switching to a big spreadsheet since the system which the wiki uses is now out of commission so doesn't get updated.

https://docs.google.com/spreadsheets/d/1AsNBmuFbJuuq1QJq-m2JAcHMw-H4RK2vJvTkAL1VSfw

We've ported all the old mods over to it but have yet to complete filling in all the details as you can see.

We're always happy to have people help since I have neglected it the past several months due to, well life :\ and it's a bitch to process.

If you wanna help out, by all means drop by our IRC #ATLauncher on EsperNet, that would be the best place :)

**Comment by dungeonmaster372** [comment]
thanks for the prompt response.  Its nice to see someone is up at this hour.  :smile: 

that would be most helpful.

**Comment by RyanTheAllmighty** [comment]
It's only 8:30pm here, still early night :P

**Comment by dungeonmaster372** [comment]
its 5:30 AM here :stuck_out_tongue: but that spreadsheet is totally confusing to me right now.

Plus the mods are still not ordered in a way that would make searching for permissions difficult.

**Comment by RyanTheAllmighty** [comment]
Yeah it's not a public spreadsheet yet that we encourage people to use. We're in the process of filling it all out, starting with everything from the old wiki, and then adding in the newer mods and then once that's all done we plan to sort it in some/many ways and then push it out for use in submissions.

**Comment by dungeonmaster372** [comment]
I dont even know where to start on there :D I will see what I can do with my spreadsheet then try to help you out here
