### ISSUE TITLE
Feature server Issues

### ISSUE THREAD

**Issue by jamesdisco13** [ATLauncher/Website-Issues#58]
Hi I've been trying to get one of the Feature server for over a week now but ever time it get down to lass then 24 hours it just say

"There are already 5 featured servers! The next available spot will be open in approximately < 1 day."

https://ci6.googleusercontent.com/proxy/Au_pHrpBBIMK0ECIIOnbawUSpGABiwcoEAlKACjtSfa4TmWZubBVzt9oe33_VaBmSOAlEQ=s0-d-e1-ft#http://i.imgur.com/84pFVjE.png

is there any way to resolve this issue please?

**Comment by RyanTheAllmighty** [comment]
Yup its first come first serve. They go very very quickly.

We'll most likely be switching to a bidding system since people don't like
what we currently have, it just means slots will most likely be much more
expensive than what you currently are trying to pay, but at least you'll
have a fair chance.

**Comment by jamesdisco13** [comment]
yes I know that but what i'm saying is the timer is just going to < 1 day and not the hours like it did before

**Comment by RyanTheAllmighty** [comment]
Oh I see.

Yes that is to prevent spawn camping as it were,. It was a measure to try
to not allow people to know exactly when it opens.

I did it just before I left for the UK so now I'm back I can try to take a
look at a better approach since what is currently there is causing grief
with some people and causing alot of double payments.
