### ISSUE TITLE
Server listing gone...

### ISSUE THREAD

**Issue by Zilacon** [ATLauncher/Website-Issues#94]
My server listing for my Yogscast Complete server is no longer on the website.
https://servers.atlauncher.com/server/APOCYogsCastComplete

Can this be fixed? Or do i have to make a new server listing?

**Comment by RyanTheAllmighty** [comment]
Hi,

Sorry for the inconvenience, no idea why it was deleted, but you'll need to re add it.

**Comment by Zilacon** [comment]
@RyanTheAllmighty Now it says cannot connect to the server when the server is online. I even tried different IP's same result so i cannot make a new listing.

IPs: HUB1.APOCGAMING.ORG / YCC.APOCGAMING.ORG

**Comment by RyanTheAllmighty** [comment]
I've looked into this and seems no service can seem to connect to the server:

https://dinnerbone.com/minecraft/tools/status/

https://mcapi.ca/query/hub1.apocgaming.org/info
https://mcapi.us/server/status?ip=hub1.apocgaming.org

https://mcapi.ca/query/ycc.apocgaming.org/info
https://mcapi.us/server/status?ip=ycc.apocgaming.org

We use mcapi.ca for our querying and it seems possibly the server is setup weirdly that nothing can read it's status.

**Comment by Zilacon** [comment]
Its hosted by Fluctis Hosting, Using a official BungeeCord version from MD_5's Jenkins. There is nothing "special" about its setup.

**Comment by RyanTheAllmighty** [comment]
Not sure then.

I'm following it up now with Yive of mcapi but do you have the direct IP of
one of the servers not through Bungee cord?

If you don't want to publicize them you can send them through
https://www.atlauncher.com/contact-us


On 9 Jan 2017 12:15 PM, "Damian Fick" <notifications@github.com> wrote:

Its hosted by Fluctis Hosting, Using a official BungeeCord version from
MD_5's Jenkins. There is nothing "special" about its setup.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ATLauncher/Website-Issues/issues/94#issuecomment-271196279>,
or mute the thread

**Comment by RyanTheAllmighty** [comment]
Alright looks like the BungeeCord server doesn't support 1.7 query methods. They fixed it in the 1153 build, but AFAIK it's not an actual release.

I'll reopen this issue for now until a fix is released

**Comment by Zilacon** [comment]
But the BC server im using is for 1.6.4 i dont think anyones going to be making a fix for that anytime soon. And why would it act up now? Its been working all this time until recently.

**Comment by RyanTheAllmighty** [comment]
Yeah no it won't be fixed on BungeeCord's end.

And it was working until we switched from our own query library to a hosted library by mcapi.ca

We moved so that uptime was more accurate, but we'll have to switch back to our own one which will mean bad uptime readings again unfortunately.

I'll close this issue once it's all fixed and running, which then you should be able to add your server back.

**Comment by Zilacon** [comment]
Alright thank you.

**Comment by RyanTheAllmighty** [comment]
Should work now

**Comment by Zilacon** [comment]
@RyanTheAllmighty Now your email system is screwed up XD
Been 25 mins and no email to verify or edit my server...
