### ISSUE TITLE
Forum search is broken

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/Website-Issues#96]
https://forums.atlauncher.com/search.php gives back a blank page with a HTTP 500 (Internal Server Error).

**Comment by RyanTheAllmighty** [comment]
I wish I could burn the forums with fire, replace it with the Discord and maybe a knowledge base and ticket system like the RR guys do.

This may be the plan with NEXT (or earlier), keeping the forums read only for SEO at minimum.

Anyway the issue lies in the forum software, it's old and not compatible with PHP 7 which breaks things like search.

I've patched it for now.
